# Generated by Django 6.0.1 on 2026-03-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_city_order_pincode_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('NEW', 'New'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('OUT_FOR_DELIVERY', 'Out for Delivery')], default='PENDING', max_length=20),
        ),
    ]
