# Generated by Django 6.0.1 on 2026-03-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material_type',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sleeves_type',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
