# Generated by Django 6.0.1 on 2026-03-22 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_reviewimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewimage',
            name='review',
        ),
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='ReviewImage',
        ),
    ]
