# Generated by Django 6.0.1 on 2026-03-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material_type',
            field=models.CharField(default='summer', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='sleeves_type',
            field=models.CharField(default='cotton', max_length=100),
            preserve_default=False,
        ),
    ]
